[tox]
envlist = pre-commit,docs-lint,docs-all

[docs]
docs_dir = {tox_root}{/}docs{/}en

[testenv:docs{,-lint,-all,-live,-en}]
# Docs are always built on Python 3.12. See also the RTD config and contribution docs.
base_python = py312
skip_install = true
setenv =
    DISABLE_MKDOCS_2_WARNING = true
    NO_MKDOCS_2_WARNING = 1
dependency_groups = docs
commands =
    !lint-!all-!live-!en : build_md_translations {posargs} en --source-code=stubs
    lint : pyspelling
    lint : markdown-checker --dir {[docs]docs_dir} --func check_broken_urls
    live : live_serve_en {posargs} --port=8043
    all : build_md_translations {posargs} en --source-code=stubs
    en : build_md_translations {posargs} en --source-code=stubs
